
CREATE PROC XEM_DU_AN
AS
BEGIN
SELECT* FROM DuAn
END
XEM_DU_AN

CREATE PROC THEM_DU_AN(
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END
THEM_DU_AN 'g','fd','2017-6-7','2017-6-12',1

CREATE PROC SUA_DU_AN(
@MA_DA INT,
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
UPDATE DuAn SET tenDA=@TEN_DA, diaDiem=@DIA_DIEM, ngayBatDau=@NGAY_BD, ngayKetThuc=@NGAY_KT, maPB=@MA_PB WHERE maDA=@MA_DA
END

CREATE PROC XOA_DU_AN(
@MA_DA INT
)
AS
BEGIN
DELETE FROM DuAn WHERE maDA=@MA_DA
END

CREATE PROC XEM_THAM_GIA(
@MA_DA INT
)
AS
BEGIN
SELECT* FROM ThamGia WHERE maDA=@MA_DA
END
XEM_THAM_GIA 1

create proc GET_EMPL_NAME (@MA_NV int) as
begin
select TenNV from NhanVien
where maNV = @MA_NV
end

CREATE PROC XEM_PHONG_BAN
AS
BEGIN
SELECT * FROM PhongBan
END

CREATE PROC THEM_PHONG_BAN(
@TEN_PB NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@MA_TP INT
)
AS
BEGIN
IF @MA_TP IN (SELECT maNV FROM NhanVien)
   INSERT INTO PhongBan(tenPB, diaDiem,maTruongPhong) VALUES (@TEN_PB,@DIA_DIEM,@MA_TP)
END

CREATE PROC SUA_PHONG_BAN(
@MA_PB INT,
@TEN_PB NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@MA_TP INT
)
AS
BEGIN
IF @MA_TP IN (SELECT maNV FROM NhanVien)
   UPDATE PhongBan SET tenPB=@TEN_PB, diaDiem=@DIA_DIEM,maTruongPhong=@MA_TP WHERE maPB=@MA_PB
END


CREATE PROC XOA_PHONG_BAN(
@MA_PB INT
)
AS
BEGIN
DELETE FROM PhongBan WHERE maPB=@MA_PB
END

CREATE PROC XEM_NV_PB(
@MA_PB INT
)
AS
BEGIN
IF(@MA_PB IN(SELECT maPB FROM PhongBan))
    SELECT * FROM NhanVien WHERE maPB=@MA_PB
END
XEM_NV_PB 1

CREATE PROC XEM_VP
AS
BEGIN
SELECT * FROM ViPham
END

CREATE PROC THEM_VP(
@LY_DO NVARCHAR(100),
@KY_LUAT NVARCHAR(100),
@NGAY_VP DATETIME,
@MA_NV INT
)
AS
BEGIN
IF @MA_NV IN (SELECT maNV FROM NhanVien)
   INSERT INTO ViPham(lyDo, hinhThucKyLuat,ngayViPham,maNV) VALUES (@LY_DO,@KY_LUAT,@NGAY_VP,@MA_NV)
END

CREATE PROC SUA_VP(
@MA_VP INT,
@LY_DO NVARCHAR(100),
@KY_LUAT NVARCHAR(100),
@NGAY_VP DATETIME,
@MA_NV INT
)
AS
BEGIN
IF @MA_NV IN (SELECT maNV FROM NhanVien)
   UPDATE ViPham SET lyDo=@LY_DO, hinhThucKyLuat=@KY_LUAT,ngayViPham=@NGAY_VP,maNV=@MA_NV WHERE maViPham=@MA_VP
END

CREATE PROC XOA_VP(
@MA_VP INT
)
AS
BEGIN
DELETE FROM ViPham WHERE maViPham=@MA_VP
END