
CREATE PROC XEM_DU_AN
AS
BEGIN
SELECT* FROM DuAn
END
XEM_DU_AN

CREATE PROC THEM_DU_AN(
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END
THEM_DU_AN 'g','fd','2017-6-7','2017-6-12',1

CREATE PROC SUA_DU_AN(
@MA_DA INT,
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
UPDATE DuAn SET tenDA=@TEN_DA, diaDiem=@DIA_DIEM, ngayBatDau=@NGAY_BD, ngayKetThuc=@NGAY_KT, maPB=@MA_PB WHERE maDA=@MA_DA
END

CREATE PROC XOA_DU_AN(
@MA_DA INT
)
AS
BEGIN
DELETE FROM DuAn WHERE maDA=@MA_DA
END

CREATE PROC XEM_THAM_GIA(
@MA_DA INT
)
AS
BEGIN
SELECT* FROM ThamGia WHERE maDA=@MA_DA
END
XEM_THAM_GIA 1

create proc GET_EMPL_NAME (@MA_NV int) as
begin
select TenNV from NhanVien
where maNV = @MA_NV
end

CREATE PROC THEM_THAM_GIA(
@MA_NV INT,
@MA_DA INT,
@SO_GIO FLOAT,
@NHIEM_VU NVARCHAR(50)
)
AS
BEGIN
IF (@MA_NV IN (SELECT maNV FROM NhanVien) AND @MA_DA IN (SELECT maDA FROM DuAn) AND @MA_DA NOT IN(SELECT @MA_DA FROM ThamGia WHERE maNV=@MA_NV))
  INSERT INTO ThamGia(maDA,maNV,soGioLam,nhiemVu) VALUES (@MA_DA,@MA_NV,@SO_GIO,@NHIEM_VU)
ELSE
  PRINT 'KHONG THEM DUOC'
END


CREATE PROC SUA_THAM_GIA(
@MA_NV INT,
@MA_DA INT,
@SO_GIO FLOAT,
@NHIEM_VU NVARCHAR(50)
)
AS
BEGIN
IF (@MA_NV IN (SELECT maNV FROM NhanVien) AND @MA_DA IN (SELECT maDA FROM DuAn))
  UPDATE ThamGia SET maDA=@MA_DA,maNV=@MA_NV,soGioLam=@SO_GIO,nhiemVu=@NHIEM_VU WHERE maDA=@MA_DA AND maNV=@MA_NV
ELSE
  PRINT 'KHONG SUA DUOC'
END
SUA_THAM_GIA 1,4,6,'huy'


CREATE PROC XOA_THAM_GIA(
@MA_DA INT,
@MA_NV INT
)
AS
BEGIN
DELETE FROM ThamGia WHERE maDA=@MA_DA AND maNV=@MA_NV
END
